# Generated by Django 5.0.4 on 2024-04-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="price_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="product_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
